#!/usr/bin/env bash
# One command from a clone to a Gameye-hosted match on your own Gameye
# account. Reads .env.gameye (copy .env.gameye.example; only
# GAMEYE_API_TOKEN is required), then:
#   1. makes sure your Gameye application exists and is set up for the game
#      server image (created, or updated if it exists), registers the image's
#      tag and waits until Gameye has it in your region;
#   2. builds the Nakama image with the plugin baked in (nakama/Dockerfile),
#      or pulls NAKAMA_IMAGE, and starts it with Postgres (compose.gameye.yml);
#   3. starts the relay (edge/, wrangler dev --env dev) and the page in
#      Gameye mode, built from this checkout and served on PAGE_PORT.
# Open the page, choose quick play: open it in a second browser or a private
# window to share a match (windows of one browser are one guest); alone, you
# get a match with bots after 12 s. Ctrl-C stops the page and the relay;
# Nakama keeps running until --down.
#
# The page is a build, not Vite's dev server: the game server in the image is
# strict (TRUST_PROXY, Dockerfile) and seats only pages of its own build id,
# which a build of the same commit has. So the image tag defaults to this
# checkout's commit (sha-<HEAD>), as release.yml publishes it.
#
#   --dry-run          print the Gameye API calls and the commands, change nothing, call nothing
#   --push-game-image  build the game server image here (linux/amd64) and push it to
#                      GAMEYE_GAME_IMAGE:GAMEYE_GAME_TAG first (docker login first)
#   --down             stop Nakama and Postgres (the database volume stays)
set -euo pipefail
cd "$(dirname "$0")/.."

usage() { sed -n '2,/^set -euo/p' "$0" | sed -e '$d' -e 's/^# \{0,1\}//'; }
DRY_RUN=0 PUSH=0 DOWN=0
for arg in "$@"; do
  case $arg in
    --dry-run) DRY_RUN=1 ;;
    --push-game-image) PUSH=1 ;;
    --down) DOWN=1 ;;
    -h | --help) usage; exit 0 ;;
    *) printf 'gameye-up: unknown option %s\n\n' "$arg" >&2; usage >&2; exit 2 ;;
  esac
done

say() { printf '%s\n' "$*"; }
warn() { printf 'gameye-up: warning: %s\n' "$*" >&2; }
die() { printf 'gameye-up: %s\n' "$*" >&2; exit 1; }
dry() { [ "$DRY_RUN" = 1 ]; }
# a command, or in a dry run what it would be
run() {
  if dry; then printf '  $'; printf ' %q' "$@"; printf '\n'; else "$@"; fi
}

ENV_FILE=${GAMEYE_ENV_FILE:-.env.gameye}
if [ -f "$ENV_FILE" ]; then
  set -a
  # shellcheck disable=SC1090 # the developer's own settings
  case $ENV_FILE in /* | ./* | ../*) . "$ENV_FILE" ;; *) . "./$ENV_FILE" ;; esac
  set +a
fi

GAMEYE_API_URL=${GAMEYE_API_URL:-https://api.sandbox-gameye.gameye.net}
GAMEYE_API_URL=${GAMEYE_API_URL%/}
GAMEYE_APPLICATION=${GAMEYE_APPLICATION:-scrapyard-nakama}
GAMEYE_REGION=${GAMEYE_REGION:-eu-central-1}
GAMEYE_NODE_POOL=${GAMEYE_NODE_POOL:-trial}
GAMEYE_GAME_REGISTRY=${GAMEYE_GAME_REGISTRY:-ghcr}
GAMEYE_TAG_WAIT=${GAMEYE_TAG_WAIT:-900}
PAGE_PORT=${PAGE_PORT:-4173}
RELAY_PORT=${RELAY_PORT:-8790}
FLEETMANAGER_DIR=${FLEETMANAGER_DIR:-../nakama-fleetmanager}
CONTAINER=${CONTAINER:-$(command -v docker >/dev/null 2>&1 && echo docker || echo podman)}
case $GAMEYE_GAME_REGISTRY in
  ghcr) GAMEYE_GAME_IMAGE=${GAMEYE_GAME_IMAGE:-ghcr.io/gameye/scrapyard-nakama} ;;
  dockerhub) [ -n "${GAMEYE_GAME_IMAGE:-}" ] || die "GAMEYE_GAME_REGISTRY=dockerhub needs GAMEYE_GAME_IMAGE=<your Docker Hub user>/scrapyard-nakama" ;;
  *) die "GAMEYE_GAME_REGISTRY is $GAMEYE_GAME_REGISTRY: dockerhub or ghcr" ;;
esac
commit=$(git rev-parse HEAD)
GAMEYE_GAME_TAG=${GAMEYE_GAME_TAG:-sha-$commit}
RELAY_URL=ws://localhost:$RELAY_PORT
for name in GAMEYE_APPLICATION GAMEYE_REGION GAMEYE_GAME_TAG; do
  [[ ${!name} =~ ^[A-Za-z0-9][A-Za-z0-9._-]*$ ]] || die "$name is ${!name}: letters, digits, '.', '_' and '-' only"
done
for name in PAGE_PORT RELAY_PORT GAMEYE_TAG_WAIT; do
  [[ ${!name} =~ ^[0-9]+$ ]] || die "$name is ${!name}: a number"
done
export GAMEYE_API_URL GAMEYE_APPLICATION GAMEYE_REGION GAMEYE_NODE_POOL GAMEYE_GAME_REGISTRY GAMEYE_GAME_IMAGE GAMEYE_GAME_TAG RELAY_URL

compose() { run "$CONTAINER" compose -f compose.gameye.yml "$@"; }

if [ "$DOWN" = 1 ]; then
  # compose wants every variable the file names, even to stop it
  export NAKAMA_IMAGE=${NAKAMA_IMAGE:-unused} GAMEYE_API_TOKEN=${GAMEYE_API_TOKEN:-unused} RELAY_SECRET=${RELAY_SECRET:-unused}
  compose down
  exit 0
fi

# --- settings ----------------------------------------------------------------------------------------

if [ -z "${GAMEYE_API_TOKEN:-}" ]; then
  dry || die "set GAMEYE_API_TOKEN in $ENV_FILE (copy .env.gameye.example)"
  warn "GAMEYE_API_TOKEN is unset: a real run stops here"
  GAMEYE_API_TOKEN='<GAMEYE_API_TOKEN>'
fi
if [ -z "${RELAY_SECRET:-}" ]; then
  if dry; then
    say "would generate RELAY_SECRET (32 random bytes) and add it to $ENV_FILE"
    RELAY_SECRET='<generated>'
  else
    RELAY_SECRET=$(node -e 'process.stdout.write(require("node:crypto").randomBytes(32).toString("base64url"))')
    (umask 077 && printf '\n# generated by scripts/gameye-up.sh: shared by the Nakama plugin and the relay\nRELAY_SECRET=%s\n' "$RELAY_SECRET" >> "$ENV_FILE")
    say "generated RELAY_SECRET into $ENV_FILE"
  fi
elif [ "${#RELAY_SECRET}" -lt 32 ]; then
  die "RELAY_SECRET is shorter than 32 bytes"
fi
export GAMEYE_API_TOKEN RELAY_SECRET

if ! dry; then
  for tool in git node npm curl "$CONTAINER"; do command -v "$tool" >/dev/null 2>&1 || die "$tool is not installed"; done
  "$CONTAINER" info >/dev/null 2>&1 || die "$CONTAINER isn't running"
  for port in "$PAGE_PORT" "$RELAY_PORT"; do
    node -e 'require("node:net").createServer().once("error", () => process.exit(1)).listen(+process.argv[1], "127.0.0.1", function () { this.close() })' "$port" ||
      die "port $port is taken (PAGE_PORT / RELAY_PORT in $ENV_FILE to choose another)"
  done
fi

say "Gameye: $GAMEYE_API_URL, application $GAMEYE_APPLICATION in $GAMEYE_REGION, image $GAMEYE_GAME_IMAGE:$GAMEYE_GAME_TAG ($GAMEYE_GAME_REGISTRY)"
if [ "$PUSH" = 0 ]; then
  [ "$GAMEYE_GAME_TAG" = "sha-$commit" ] || warn "GAMEYE_GAME_TAG isn't this checkout's commit (sha-$commit): the page built here may not match the image's build, and the game server would refuse it (\"Game updated\")"
  [ -z "$(git status --porcelain -- game/src game/server game/package-lock.json)" ] || warn "game/ has uncommitted changes: the page built here won't match the image at $GAMEYE_GAME_TAG. Commit and let release.yml publish it, or use --push-game-image"
fi

# --- the game server image, when it's yours to push ---------------------------------------------------

if [ "$PUSH" = 1 ]; then
  ref=$GAMEYE_GAME_IMAGE
  [[ ${ref%%/*} == *[.:]* ]] || ref=docker.io/$ref # Docker Hub's repositories are named without the host
  say "building the game server image for linux/amd64 and pushing $ref:$GAMEYE_GAME_TAG"
  if [ "$CONTAINER" = docker ]; then
    run docker buildx build --platform linux/amd64 -t "$ref:$GAMEYE_GAME_TAG" --push .
  else
    run "$CONTAINER" build --platform linux/amd64 -t "$ref:$GAMEYE_GAME_TAG" .
    run "$CONTAINER" push "$ref:$GAMEYE_GAME_TAG"
  fi
  say "make sure $ref is public: Gameye pulls it without credentials"
fi

# --- the Gameye application and its tag ----------------------------------------------------------------

API_STATUS='' API_BODY=''
if ! dry; then
  api_dir=$(mktemp -d)
  trap 'rm -rf "$api_dir"' EXIT
  # the token goes to curl in a file, never on its command line
  (umask 077 && printf 'Authorization: Bearer %s\n' "$GAMEYE_API_TOKEN" > "$api_dir/headers")
fi

api() { # METHOD PATH [JSON]: sets API_STATUS and API_BODY
  local method=$1 path=$2 body=${3:-}
  if dry; then
    printf '  %-4s %s%s\n' "$method" "$GAMEYE_API_URL" "$path"
    [ -z "$body" ] || printf '       %s\n' "$body"
    API_STATUS=dry API_BODY=''
    return
  fi
  local args=(-sS --max-time 30 -o "$api_dir/body" -w '%{http_code}' -X "$method" -H "@$api_dir/headers")
  [ -z "$body" ] || args+=(-H 'Content-Type: application/json' --data-binary "$body")
  API_STATUS=$(curl "${args[@]}" "$GAMEYE_API_URL$path") || die "couldn't reach $GAMEYE_API_URL"
  API_BODY=$(cat "$api_dir/body")
}
# a question about API_BODY, answered by a node expression over `body` (the parsed JSON) and `arg`
ask() { API_BODY=$API_BODY node -e 'let body; try { body = JSON.parse(process.env.API_BODY) } catch {} const arg = process.argv[2]; const v = eval(process.argv[1]); if (v !== undefined && v !== null && v !== false) process.stdout.write(String(v))' "$1" "${2:-}"; }

ghcr_refused() {
  die "Gameye refused the GHCR image $GAMEYE_GAME_IMAGE (409: $1).
Gameye's GHCR integration currently takes only images whose GitHub owner has your Gameye
organization's name, public ones too; a fix is pending. Use Docker Hub meanwhile:
  1. docker login, with your Docker Hub account
  2. in $ENV_FILE: GAMEYE_GAME_REGISTRY=dockerhub and GAMEYE_GAME_IMAGE=<your Docker Hub user>/scrapyard-nakama
  3. scripts/gameye-up.sh --push-game-image   (builds the image from this checkout and pushes it; make the repository public)"
}
refused() { # WHAT SCOPE
  local message
  message=$(ask 'body && (body.message || body.details)')
  case $API_STATUS in
    401) die "$1: Gameye refused the token (401). Check GAMEYE_API_TOKEN, and that it was made for $GAMEYE_API_URL (sandbox and production tokens differ)" ;;
    403) die "$1: the token lacks the $2 scope (403). Make a token with application:read, application:write, regions:read, session:start, session:read and session:stop" ;;
    409) if [[ $API_BODY == *[Oo]wner* ]]; then ghcr_refused "${message:-owner mismatch}"; fi
         die "$1: conflict (409)${message:+: $message}" ;;
    *) die "$1: HTTP $API_STATUS${message:+: $message}" ;;
  esac
}

app_body() { # post | put
  node -e '
    const e = process.env
    const app = {
      registry: e.GAMEYE_GAME_REGISTRY, repository: e.GAMEYE_GAME_IMAGE, tagKeep: 2, networkMode: "bridge",
      limits: { cpu: 0.5, ram: 512 }, reservation: { cpu: 0.5, ram: 512 }, nodePool: e.GAMEYE_NODE_POOL,
      regions: [e.GAMEYE_REGION], ports: [{ requested: 7360, protocol: "tcp", tls: false }],
    }
    process.stdout.write(JSON.stringify(process.argv[1] === "post" ? { name: e.GAMEYE_APPLICATION, ...app } : app))' "$1"
}
app=$GAMEYE_APPLICATION tag=$GAMEYE_GAME_TAG

dry && say "Gameye API calls (token from GAMEYE_API_TOKEN, never printed):"
api GET /application
if dry; then
  say "  then, if $app isn't listed, create it:"
  api POST /application "$(app_body post)"
  say "  or, if it is, bring it up to date:"
  api PUT "/application/$app" "$(app_body put)"
else
  [ "$API_STATUS" = 200 ] || refused "Listing your applications" application:read
  if [ -n "$(ask '(body?.applications ?? []).some((a) => a.name === arg)' "$app")" ]; then
    api PUT "/application/$app" "$(app_body put)"
    [[ $API_STATUS == 20? ]] || refused "Updating application $app" application:write
    say "application $app: updated"
  else
    api POST /application "$(app_body post)"
    if [ "$API_STATUS" = 409 ] && [[ $API_BODY != *[Oo]wner* ]]; then # made meanwhile
      api PUT "/application/$app" "$(app_body put)"
      [[ $API_STATUS == 20? ]] || refused "Updating application $app" application:write
    elif [[ $API_STATUS != 20? ]]; then
      refused "Creating application $app" application:write
    fi
    say "application $app: created"
  fi
fi

# Is the tag in the registry? A hint only: registering it below is what counts.
api GET "/application/$app/tags/available?page=1&pageSize=1000"
if ! dry; then
  case $API_STATUS in
    200) [ -n "$(ask '(body?.tags ?? []).some((t) => t.version === arg)' "$tag")" ] ||
           warn "$tag is not among the first 1000 tags Gameye lists for it; registering it anyway" ;;
    401 | 403) refused "Listing $app's registry tags" application:read ;;
    *) warn "couldn't list $app's registry tags (HTTP $API_STATUS); going on" ;;
  esac
fi

api POST "/application/$app/tags" "{\"tag\":\"$tag\"}"
if ! dry; then
  case $API_STATUS in
    20?) say "tag $tag: registered" ;;
    404) die "Gameye can't find $GAMEYE_GAME_IMAGE:$tag (404). release.yml publishes sha-<commit> for each push to main once CI passes; push this commit and wait for it, set GAMEYE_GAME_TAG to a published tag, or build and push your own with --push-game-image" ;;
    *) refused "Registering tag $tag" application:write ;;
  esac
fi

dry && say "  then every 10 s until it says {\"exists\":true} (at most $GAMEYE_TAG_WAIT s):"
api GET "/tag/$GAMEYE_REGION/$app/$tag"
if ! dry; then
  waited=0
  while :; do
    case $API_STATUS in
      200) [ -z "$(ask 'body?.exists === true')" ] || break ;;
      404) ;; # not there yet
      *) refused "Checking tag $tag in $GAMEYE_REGION" regions:read ;;
    esac
    [ "$waited" -lt "$GAMEYE_TAG_WAIT" ] || die "tag $tag still isn't ready in $GAMEYE_REGION after $GAMEYE_TAG_WAIT s (HTTP $API_STATUS); run again to keep waiting, or check the image in Gameye's dashboard"
    [ "$waited" -gt 0 ] || say "waiting for Gameye to have $tag in $GAMEYE_REGION..."
    sleep 10
    waited=$((waited + 10))
    api GET "/tag/$GAMEYE_REGION/$app/$tag"
  done
  say "tag $tag: ready in $GAMEYE_REGION"
  rm -rf "$api_dir"
fi

# --- Nakama and Postgres --------------------------------------------------------------------------------

if [ -z "${NAKAMA_IMAGE:-}" ]; then
  NAKAMA_IMAGE=scrapyard-nakama-backend:local
  build=(build -f nakama/Dockerfile -t "$NAKAMA_IMAGE")
  # TODO: drop with the replace in go.mod once nakama-fleetmanager v0.1.0 is published
  if grep -q '^replace github.com/Gameye/nakama-fleetmanager' nakama/modules-src/go.mod; then
    dry || [ -f "$FLEETMANAGER_DIR/go.mod" ] || die "no Fleet Manager checkout at $FLEETMANAGER_DIR: clone github.com/Gameye/nakama-fleetmanager beside this repo, or set FLEETMANAGER_DIR"
    build+=(--build-context "fleetmanager=$FLEETMANAGER_DIR")
  fi
  run "$CONTAINER" "${build[@]}" .
else
  run "$CONTAINER" pull "$NAKAMA_IMAGE"
fi
export NAKAMA_IMAGE
compose up -d
if ! dry; then
  for _ in $(seq 60); do curl -fsS -o /dev/null http://127.0.0.1:7350/healthcheck 2>/dev/null && break; sleep 2; done
  curl -fsS -o /dev/null http://127.0.0.1:7350/healthcheck 2>/dev/null || {
    "$CONTAINER" compose -f compose.gameye.yml logs --tail 30 nakama >&2
    die "Nakama didn't come up (logs above)"
  }
  say "Nakama: http://127.0.0.1:7350 (console http://127.0.0.1:7351, admin / password)"
fi

# --- the relay and the page ------------------------------------------------------------------------------

[ -d node_modules ] || run npm ci --no-audit --no-fund
[ -d game/node_modules ] || run npm --prefix game ci --no-audit --no-fund

# wrangler dev reads the relay's secret from edge/.dev.vars (gitignored)
VARS=edge/.dev.vars
MARK='# written by scripts/gameye-up.sh'
if dry; then
  say "would write RELAY_SECRET to $VARS"
else
  [ ! -f "$VARS" ] || head -1 "$VARS" | grep -qxF "$MARK" || die "$VARS exists and wasn't written by this script: move it away and run again"
  (umask 077 && printf '%s\nRELAY_SECRET=%s\n' "$MARK" "$RELAY_SECRET" > "$VARS")
fi

# the page: Gameye mode, against this Nakama (Vite takes these over game/.env*)
export VITE_MATCHMAKER=gameye VITE_NAKAMA_HOST=127.0.0.1 VITE_NAKAMA_PORT=7350 VITE_NAKAMA_SSL=false VITE_NAKAMA_KEY=defaultkey
(cd game && run npx vite build --outDir dist-gameye --emptyOutDir --logLevel warn)

if dry; then
  (cd game && run npx vite preview --outDir dist-gameye --host localhost --port "$PAGE_PORT" --strictPort)
  run npx wrangler dev -c edge/wrangler.jsonc --env dev --ip 127.0.0.1 --port "$RELAY_PORT"
  say "dry run: nothing was created or started"
  exit 0
fi

trap 'kill 0' INT TERM
WRANGLER_SEND_METRICS=false npx wrangler dev -c edge/wrangler.jsonc --env dev --ip 127.0.0.1 --port "$RELAY_PORT" &
(cd game && npx vite preview --outDir dist-gameye --host localhost --port "$PAGE_PORT" --strictPort) &
say ""
say "Open http://localhost:$PAGE_PORT and choose quick play (open it in a second browser or a private window to share a match)."
say "Relay: $RELAY_URL. Ctrl-C stops the page and the relay; scripts/gameye-up.sh --down stops Nakama."
wait
